package co.com.soinsoftware.schoolmanagement.hibernate;

// Generated 19-abr-2015 18:35:39 by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * Bzclassroomxuser generated by hbm2java
 */
@SuppressWarnings({ "serial" })
public class Bzclassroomxuser implements java.io.Serializable {

	private BzclassroomxuserId id;
	private Bzclassroom bzclassroom;
	private Bzuser bzuser;
	private Date creation;
	private Date updated;
	private boolean enabled;

	public Bzclassroomxuser() {
	}

	public Bzclassroomxuser(BzclassroomxuserId id, Bzclassroom bzclassroom,
			Bzuser bzuser, Date creation, Date updated, boolean enabled) {
		this.id = id;
		this.bzclassroom = bzclassroom;
		this.bzuser = bzuser;
		this.creation = creation;
		this.updated = updated;
		this.enabled = enabled;
	}

	public BzclassroomxuserId getId() {
		return this.id;
	}

	public void setId(BzclassroomxuserId id) {
		this.id = id;
	}

	public Bzclassroom getBzclassroom() {
		return this.bzclassroom;
	}

	public void setBzclassroom(Bzclassroom bzclassroom) {
		this.bzclassroom = bzclassroom;
	}

	public Bzuser getBzuser() {
		return this.bzuser;
	}

	public void setBzuser(Bzuser bzuser) {
		this.bzuser = bzuser;
	}

	public Date getCreation() {
		return this.creation;
	}

	public void setCreation(Date creation) {
		this.creation = creation;
	}

	public Date getUpdated() {
		return this.updated;
	}

	public void setUpdated(Date updated) {
		this.updated = updated;
	}

	public boolean isEnabled() {
		return this.enabled;
	}

	public void setEnabled(boolean enabled) {
		this.enabled = enabled;
	}

}
