package co.com.soinsoftware.schoolmanagement.hibernate;

// Generated 13-may-2016 10:19:39 by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;

/**
 * Bzfinalnote generated by hbm2java
 */
@SuppressWarnings({ "serial" })
public class Bzfinalnote implements java.io.Serializable {

	private BzfinalnoteId id;
	private BigDecimal value;
	private Date creation;
	private Date updated;
	private boolean enabled;

	public Bzfinalnote() {
	}

	public Bzfinalnote(BzfinalnoteId id, BigDecimal value, Date creation,
			Date updated, boolean enabled) {
		this.id = id;
		this.value = value;
		this.creation = creation;
		this.updated = updated;
		this.enabled = enabled;
	}

	public BzfinalnoteId getId() {
		return this.id;
	}

	public void setId(BzfinalnoteId id) {
		this.id = id;
	}

	public BigDecimal getValue() {
		return this.value;
	}

	public void setValue(BigDecimal value) {
		this.value = value;
	}

	public Date getCreation() {
		return this.creation;
	}

	public void setCreation(Date creation) {
		this.creation = creation;
	}

	public Date getUpdated() {
		return this.updated;
	}

	public void setUpdated(Date updated) {
		this.updated = updated;
	}

	public boolean isEnabled() {
		return this.enabled;
	}

	public void setEnabled(boolean enabled) {
		this.enabled = enabled;
	}

}
