package co.com.soinsoftware.schoolmanagement.hibernate;

// Generated 13-may-2016 10:14:39 by Hibernate Tools 4.3.1

/**
 * BzfinalnoteId generated by hbm2java
 */
@SuppressWarnings({ "serial" })
public class BzfinalnoteId implements java.io.Serializable {

	private int idClass;
	private int idUser;
	private int idPeriod;

	public BzfinalnoteId() {
	}

	public BzfinalnoteId(int idClass, int idUser, int idPeriod) {
		this.idClass = idClass;
		this.idUser = idUser;
		this.idPeriod = idPeriod;
	}

	public int getIdClass() {
		return this.idClass;
	}

	public void setIdClass(int idClass) {
		this.idClass = idClass;
	}

	public int getIdUser() {
		return this.idUser;
	}

	public void setIdUser(int idUser) {
		this.idUser = idUser;
	}

	public int getIdPeriod() {
		return this.idPeriod;
	}

	public void setIdPeriod(int idPeriod) {
		this.idPeriod = idPeriod;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + idClass;
		result = prime * result + idPeriod;
		result = prime * result + idUser;
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		BzfinalnoteId other = (BzfinalnoteId) obj;
		if (idClass != other.idClass)
			return false;
		if (idPeriod != other.idPeriod)
			return false;
		if (idUser != other.idUser)
			return false;
		return true;
	}
}