package co.com.soinsoftware.schoolmanagement.hibernate;

// Generated 19-abr-2015 18:35:39 by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * Bznotedefinition generated by hbm2java
 */
@SuppressWarnings({ "serial" })
public class Bznotedefinition implements java.io.Serializable {

	private Integer id;
	private Bzclass bzclass;
	private Bzperiod bzperiod;
	private String name;
	private String description;
	private Integer value;
	private Date creation;
	private Date updated;
	private boolean enabled;

	public Bznotedefinition() {
	}

	public Bznotedefinition(Bzclass bzclass, Bzperiod bzperiod, String name,
			String description, Integer value, Date creation, Date updated,
			boolean enabled) {
		this.bzclass = bzclass;
		this.bzperiod = bzperiod;
		this.name = name;
		this.description = description;
		this.value = value;
		this.creation = creation;
		this.updated = updated;
		this.enabled = enabled;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Bzclass getBzclass() {
		return this.bzclass;
	}

	public void setBzclass(Bzclass bzclass) {
		this.bzclass = bzclass;
	}

	public Bzperiod getBzperiod() {
		return this.bzperiod;
	}

	public void setBzperiod(Bzperiod bzperiod) {
		this.bzperiod = bzperiod;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Integer getValue() {
		return this.value;
	}

	public void setValue(Integer value) {
		this.value = value;
	}

	public Date getCreation() {
		return this.creation;
	}

	public void setCreation(Date creation) {
		this.creation = creation;
	}

	public Date getUpdated() {
		return this.updated;
	}

	public void setUpdated(Date updated) {
		this.updated = updated;
	}

	public boolean isEnabled() {
		return this.enabled;
	}

	public void setEnabled(boolean enabled) {
		this.enabled = enabled;
	}

}
