package co.com.soinsoftware.schoolmanagement.hibernate;

// Generated 19-abr-2015 18:35:39 by Hibernate Tools 4.3.1

/**
 * BzschoolxuserId generated by hbm2java
 */
@SuppressWarnings({ "serial" })
public class BzschoolxuserId implements java.io.Serializable {

	private int idSchool;
	private int idUser;

	public BzschoolxuserId() {
	}

	public BzschoolxuserId(int idSchool, int idUser) {
		this.idSchool = idSchool;
		this.idUser = idUser;
	}

	public int getIdSchool() {
		return this.idSchool;
	}

	public void setIdSchool(int idSchool) {
		this.idSchool = idSchool;
	}

	public int getIdUser() {
		return this.idUser;
	}

	public void setIdUser(int idUser) {
		this.idUser = idUser;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof BzschoolxuserId))
			return false;
		BzschoolxuserId castOther = (BzschoolxuserId) other;

		return (this.getIdSchool() == castOther.getIdSchool())
				&& (this.getIdUser() == castOther.getIdUser());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdSchool();
		result = 37 * result + this.getIdUser();
		return result;
	}

}
