package co.com.soinsoftware.schoolmanagement.hibernate;

// Generated 19-abr-2015 18:35:39 by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Bzschool generated by hbm2java
 */
@SuppressWarnings({ "serial", "rawtypes" })
public class Bzschool implements java.io.Serializable {

	private Integer id;
	private Cnnote cnnote;
	private String code;
	private String name;
	private String photo;
	private Integer period;
	private String nit;
	private String dane;
	private Date creation;
	private Date updated;
	private boolean enabled;
	private Set bzschoolxusers = new HashSet(0);
	private Set bzclassrooms = new HashSet(0);

	public Bzschool() {
	}

	public Bzschool(Cnnote cnnote, String code, String name, String photo,
			Integer period, String nit, String dane, Date creation,
			Date updated, boolean enabled) {
		this.cnnote = cnnote;
		this.code = code;
		this.name = name;
		this.photo = photo;
		this.period = period;
		this.nit = nit;
		this.dane = dane;
		this.creation = creation;
		this.updated = updated;
		this.enabled = enabled;
	}

	public Bzschool(Cnnote cnnote, String code, String name, String photo,
			Integer period, String nit, String dane, Date creation,
			Date updated, boolean enabled, Set bzschoolxusers, Set bzclassrooms) {
		this.cnnote = cnnote;
		this.code = code;
		this.name = name;
		this.photo = photo;
		this.period = period;
		this.nit = nit;
		this.dane = dane;
		this.creation = creation;
		this.updated = updated;
		this.enabled = enabled;
		this.bzschoolxusers = bzschoolxusers;
		this.bzclassrooms = bzclassrooms;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Cnnote getCnnote() {
		return cnnote;
	}

	public void setCnnote(Cnnote cnnote) {
		this.cnnote = cnnote;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getPhoto() {
		return this.photo;
	}

	public void setPhoto(String photo) {
		this.photo = photo;
	}

	public Integer getPeriod() {
		return period;
	}

	public void setPeriod(Integer period) {
		this.period = period;
	}

	public String getNit() {
		return this.nit;
	}

	public void setNit(String nit) {
		this.nit = nit;
	}

	public String getDane() {
		return this.dane;
	}

	public void setDane(String dane) {
		this.dane = dane;
	}

	public Date getCreation() {
		return this.creation;
	}

	public void setCreation(Date creation) {
		this.creation = creation;
	}

	public Date getUpdated() {
		return this.updated;
	}

	public void setUpdated(Date updated) {
		this.updated = updated;
	}

	public boolean isEnabled() {
		return this.enabled;
	}

	public void setEnabled(boolean enabled) {
		this.enabled = enabled;
	}

	public Set getBzschoolxusers() {
		return this.bzschoolxusers;
	}

	public void setBzschoolxusers(Set bzschoolxusers) {
		this.bzschoolxusers = bzschoolxusers;
	}

	public Set getBzclassrooms() {
		return this.bzclassrooms;
	}

	public void setBzclassrooms(Set bzclassrooms) {
		this.bzclassrooms = bzclassrooms;
	}

}
