package co.com.soinsoftware.schoolmanagement.hibernate;

// Generated 19-abr-2015 18:35:39 by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Bzuser generated by hbm2java
 */
@SuppressWarnings({ "serial", "rawtypes" })
public class Bzuser implements java.io.Serializable {

	private Integer id;
	private Bzuser bzuserByIdGuardian2;
	private Bzuser bzuserByIdGuardian1;
	private String documentNumber;
	private String documentType;
	private String name;
	private String lastName;
	private Date born;
	private String address;
	private long phone1;
	private Long phone2;
	private String password;
	private String gender;
	private String photo;
	private Date creation;
	private Date updated;
	private boolean enabled;
	private Set bzschoolxusers = new HashSet(0);
	private Set bzclassroomxusers = new HashSet(0);
	private Set bzclasses = new HashSet(0);
	private Set bzusersForIdGuardian2 = new HashSet(0);
	private Set bzclassrooms = new HashSet(0);
	private Set bzusersForIdGuardian1 = new HashSet(0);
	private Set bzuserxusertypes = new HashSet(0);

	public Bzuser() {
	}

	public Bzuser(String documentNumber, String documentType, String name,
			String lastName, Date born, String address, long phone1,
			String gender, Date creation, Date updated, boolean enabled) {
		this.documentNumber = documentNumber;
		this.documentType = documentType;
		this.name = name;
		this.lastName = lastName;
		this.born = born;
		this.address = address;
		this.phone1 = phone1;
		this.gender = gender;
		this.creation = creation;
		this.updated = updated;
		this.enabled = enabled;
	}

	public Bzuser(Bzuser bzuserByIdGuardian2, Bzuser bzuserByIdGuardian1,
			String documentNumber, String documentType, String name,
			String lastName, Date born, String address, long phone1,
			Long phone2, String password, String gender, String photo,
			Date creation, Date updated, boolean enabled, Set bzschoolxusers,
			Set bzclassroomxusers, Set bzclasses, Set bzusersForIdGuardian2,
			Set bzclassrooms, Set bzusersForIdGuardian1, Set bzuserxusertypes) {
		this.bzuserByIdGuardian2 = bzuserByIdGuardian2;
		this.bzuserByIdGuardian1 = bzuserByIdGuardian1;
		this.documentNumber = documentNumber;
		this.documentType = documentType;
		this.name = name;
		this.lastName = lastName;
		this.born = born;
		this.address = address;
		this.phone1 = phone1;
		this.phone2 = phone2;
		this.password = password;
		this.gender = gender;
		this.photo = photo;
		this.creation = creation;
		this.updated = updated;
		this.enabled = enabled;
		this.bzschoolxusers = bzschoolxusers;
		this.bzclassroomxusers = bzclassroomxusers;
		this.bzclasses = bzclasses;
		this.bzusersForIdGuardian2 = bzusersForIdGuardian2;
		this.bzclassrooms = bzclassrooms;
		this.bzusersForIdGuardian1 = bzusersForIdGuardian1;
		this.bzuserxusertypes = bzuserxusertypes;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Bzuser getBzuserByIdGuardian2() {
		return this.bzuserByIdGuardian2;
	}

	public void setBzuserByIdGuardian2(Bzuser bzuserByIdGuardian2) {
		this.bzuserByIdGuardian2 = bzuserByIdGuardian2;
	}

	public Bzuser getBzuserByIdGuardian1() {
		return this.bzuserByIdGuardian1;
	}

	public void setBzuserByIdGuardian1(Bzuser bzuserByIdGuardian1) {
		this.bzuserByIdGuardian1 = bzuserByIdGuardian1;
	}

	public String getDocumentNumber() {
		return this.documentNumber;
	}

	public void setDocumentNumber(String documentNumber) {
		this.documentNumber = documentNumber;
	}

	public String getDocumentType() {
		return this.documentType;
	}

	public void setDocumentType(String documentType) {
		this.documentType = documentType;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public Date getBorn() {
		return this.born;
	}

	public void setBorn(Date born) {
		this.born = born;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public long getPhone1() {
		return this.phone1;
	}

	public void setPhone1(long phone1) {
		this.phone1 = phone1;
	}

	public Long getPhone2() {
		return this.phone2;
	}

	public void setPhone2(Long phone2) {
		this.phone2 = phone2;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getGender() {
		return this.gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	public String getPhoto() {
		return this.photo;
	}

	public void setPhoto(String photo) {
		this.photo = photo;
	}

	public Date getCreation() {
		return this.creation;
	}

	public void setCreation(Date creation) {
		this.creation = creation;
	}

	public Date getUpdated() {
		return this.updated;
	}

	public void setUpdated(Date updated) {
		this.updated = updated;
	}

	public boolean isEnabled() {
		return this.enabled;
	}

	public void setEnabled(boolean enabled) {
		this.enabled = enabled;
	}

	public Set getBzschoolxusers() {
		return this.bzschoolxusers;
	}

	public void setBzschoolxusers(Set bzschoolxusers) {
		this.bzschoolxusers = bzschoolxusers;
	}

	public Set getBzclassroomxusers() {
		return this.bzclassroomxusers;
	}

	public void setBzclassroomxusers(Set bzclassroomxusers) {
		this.bzclassroomxusers = bzclassroomxusers;
	}

	public Set getBzclasses() {
		return this.bzclasses;
	}

	public void setBzclasses(Set bzclasses) {
		this.bzclasses = bzclasses;
	}

	public Set getBzusersForIdGuardian2() {
		return this.bzusersForIdGuardian2;
	}

	public void setBzusersForIdGuardian2(Set bzusersForIdGuardian2) {
		this.bzusersForIdGuardian2 = bzusersForIdGuardian2;
	}

	public Set getBzclassrooms() {
		return this.bzclassrooms;
	}

	public void setBzclassrooms(Set bzclassrooms) {
		this.bzclassrooms = bzclassrooms;
	}

	public Set getBzusersForIdGuardian1() {
		return this.bzusersForIdGuardian1;
	}

	public void setBzusersForIdGuardian1(Set bzusersForIdGuardian1) {
		this.bzusersForIdGuardian1 = bzusersForIdGuardian1;
	}

	public Set getBzuserxusertypes() {
		return this.bzuserxusertypes;
	}

	public void setBzuserxusertypes(Set bzuserxusertypes) {
		this.bzuserxusertypes = bzuserxusertypes;
	}

}
