package co.com.soinsoftware.schoolmanagement.hibernate;

// Generated 19-abr-2015 18:35:39 by Hibernate Tools 4.3.1

/**
 * BzuserxusertypeId generated by hbm2java
 */
@SuppressWarnings({ "serial" })
public class BzuserxusertypeId implements java.io.Serializable {

	private int idUser;
	private int idUserType;

	public BzuserxusertypeId() {
	}

	public BzuserxusertypeId(int idUser, int idUserType) {
		this.idUser = idUser;
		this.idUserType = idUserType;
	}

	public int getIdUser() {
		return this.idUser;
	}

	public void setIdUser(int idUser) {
		this.idUser = idUser;
	}

	public int getIdUserType() {
		return this.idUserType;
	}

	public void setIdUserType(int idUserType) {
		this.idUserType = idUserType;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof BzuserxusertypeId))
			return false;
		BzuserxusertypeId castOther = (BzuserxusertypeId) other;

		return (this.getIdUser() == castOther.getIdUser())
				&& (this.getIdUserType() == castOther.getIdUserType());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdUser();
		result = 37 * result + this.getIdUserType();
		return result;
	}

}
