package co.com.soinsoftware.schoolmanagement.hibernate;

// Generated 19-abr-2015 18:35:39 by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Cnusertype generated by hbm2java
 */
@SuppressWarnings({ "serial", "rawtypes" })
public class Cnusertype implements java.io.Serializable {

	private Integer id;
	private String code;
	private String name;
	private Date creation;
	private Date updated;
	private boolean enabled;
	private Set cnusertypexaccesses = new HashSet(0);
	private Set bzuserxusertypes = new HashSet(0);

	public Cnusertype() {
	}

	public Cnusertype(String code, String name, Date creation, Date updated,
			boolean enabled) {
		this.code = code;
		this.name = name;
		this.creation = creation;
		this.updated = updated;
		this.enabled = enabled;
	}

	public Cnusertype(String code, String name, Date creation, Date updated,
			boolean enabled, Set cnuserttypexaccesses, Set bzuserxusertypes) {
		this.code = code;
		this.name = name;
		this.creation = creation;
		this.updated = updated;
		this.enabled = enabled;
		this.cnusertypexaccesses = cnuserttypexaccesses;
		this.bzuserxusertypes = bzuserxusertypes;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Date getCreation() {
		return this.creation;
	}

	public void setCreation(Date creation) {
		this.creation = creation;
	}

	public Date getUpdated() {
		return this.updated;
	}

	public void setUpdated(Date updated) {
		this.updated = updated;
	}

	public boolean isEnabled() {
		return this.enabled;
	}

	public void setEnabled(boolean enabled) {
		this.enabled = enabled;
	}

	public Set getCnusertypexaccesses() {
		return this.cnusertypexaccesses;
	}

	public void setCnusertypexaccesses(Set cnusertypexaccesses) {
		this.cnusertypexaccesses = cnusertypexaccesses;
	}

	public Set getBzuserxusertypes() {
		return this.bzuserxusertypes;
	}

	public void setBzuserxusertypes(Set bzuserxusertypes) {
		this.bzuserxusertypes = bzuserxusertypes;
	}

}
