package co.com.carpcosoftware.schoolmanagement.hibernate;

// Generated 19-abr-2015 18:35:39 by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Bzclassroom generated by hbm2java
 */
public class Bzclassroom implements java.io.Serializable {

	private Integer id;
	private Bzgrade bzgrade;
	private Bzschool bzschool;
	private Bzuser bzuser;
	private Bzyear bzyear;
	private String code;
	private String name;
	private Date creation;
	private Date updated;
	private boolean enabled;
	private Set bzclasses = new HashSet(0);
	private Set bzclassroomxusers = new HashSet(0);

	public Bzclassroom() {
	}

	public Bzclassroom(Bzgrade bzgrade, Bzschool bzschool, Bzuser bzuser,
			Bzyear bzyear, String code, String name, Date creation,
			Date updated, boolean enabled) {
		this.bzgrade = bzgrade;
		this.bzschool = bzschool;
		this.bzuser = bzuser;
		this.bzyear = bzyear;
		this.code = code;
		this.name = name;
		this.creation = creation;
		this.updated = updated;
		this.enabled = enabled;
	}

	public Bzclassroom(Bzgrade bzgrade, Bzschool bzschool, Bzuser bzuser,
			Bzyear bzyear, String code, String name, Date creation,
			Date updated, boolean enabled, Set bzclasses, Set bzclassroomxusers) {
		this.bzgrade = bzgrade;
		this.bzschool = bzschool;
		this.bzuser = bzuser;
		this.bzyear = bzyear;
		this.code = code;
		this.name = name;
		this.creation = creation;
		this.updated = updated;
		this.enabled = enabled;
		this.bzclasses = bzclasses;
		this.bzclassroomxusers = bzclassroomxusers;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Bzgrade getBzgrade() {
		return this.bzgrade;
	}

	public void setBzgrade(Bzgrade bzgrade) {
		this.bzgrade = bzgrade;
	}

	public Bzschool getBzschool() {
		return this.bzschool;
	}

	public void setBzschool(Bzschool bzschool) {
		this.bzschool = bzschool;
	}

	public Bzuser getBzuser() {
		return this.bzuser;
	}

	public void setBzuser(Bzuser bzuser) {
		this.bzuser = bzuser;
	}

	public Bzyear getBzyear() {
		return this.bzyear;
	}

	public void setBzyear(Bzyear bzyear) {
		this.bzyear = bzyear;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Date getCreation() {
		return this.creation;
	}

	public void setCreation(Date creation) {
		this.creation = creation;
	}

	public Date getUpdated() {
		return this.updated;
	}

	public void setUpdated(Date updated) {
		this.updated = updated;
	}

	public boolean isEnabled() {
		return this.enabled;
	}

	public void setEnabled(boolean enabled) {
		this.enabled = enabled;
	}

	public Set getBzclasses() {
		return this.bzclasses;
	}

	public void setBzclasses(Set bzclasses) {
		this.bzclasses = bzclasses;
	}

	public Set getBzclassroomxusers() {
		return this.bzclassroomxusers;
	}

	public void setBzclassroomxusers(Set bzclassroomxusers) {
		this.bzclassroomxusers = bzclassroomxusers;
	}

}
