package co.com.carpcosoftware.schoolmanagement.hibernate;

// Generated 19-abr-2015 18:35:39 by Hibernate Tools 4.3.1

/**
 * BznotevalueId generated by hbm2java
 */
public class BznotevalueId implements java.io.Serializable {

	private int idNoteDefinition;
	private int idUser;

	public BznotevalueId() {
	}

	public BznotevalueId(int idNoteDefinition, int idUser) {
		this.idNoteDefinition = idNoteDefinition;
		this.idUser = idUser;
	}

	public int getIdNoteDefinition() {
		return this.idNoteDefinition;
	}

	public void setIdNoteDefinition(int idNoteDefinition) {
		this.idNoteDefinition = idNoteDefinition;
	}

	public int getIdUser() {
		return this.idUser;
	}

	public void setIdUser(int idUser) {
		this.idUser = idUser;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof BznotevalueId))
			return false;
		BznotevalueId castOther = (BznotevalueId) other;

		return (this.getIdNoteDefinition() == castOther.getIdNoteDefinition())
				&& (this.getIdUser() == castOther.getIdUser());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdNoteDefinition();
		result = 37 * result + this.getIdUser();
		return result;
	}

}
