package co.com.carpcosoftware.schoolmanagement.hibernate;

// Generated 19-abr-2015 18:35:39 by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * Bzschoolxuser generated by hbm2java
 */
public class Bzschoolxuser implements java.io.Serializable {

	private BzschoolxuserId id;
	private Bzschool bzschool;
	private Bzuser bzuser;
	private Date creation;
	private Date updated;
	private boolean enabled;

	public Bzschoolxuser() {
	}

	public Bzschoolxuser(BzschoolxuserId id, Bzschool bzschool, Bzuser bzuser,
			Date creation, Date updated, boolean enabled) {
		this.id = id;
		this.bzschool = bzschool;
		this.bzuser = bzuser;
		this.creation = creation;
		this.updated = updated;
		this.enabled = enabled;
	}

	public BzschoolxuserId getId() {
		return this.id;
	}

	public void setId(BzschoolxuserId id) {
		this.id = id;
	}

	public Bzschool getBzschool() {
		return this.bzschool;
	}

	public void setBzschool(Bzschool bzschool) {
		this.bzschool = bzschool;
	}

	public Bzuser getBzuser() {
		return this.bzuser;
	}

	public void setBzuser(Bzuser bzuser) {
		this.bzuser = bzuser;
	}

	public Date getCreation() {
		return this.creation;
	}

	public void setCreation(Date creation) {
		this.creation = creation;
	}

	public Date getUpdated() {
		return this.updated;
	}

	public void setUpdated(Date updated) {
		this.updated = updated;
	}

	public boolean isEnabled() {
		return this.enabled;
	}

	public void setEnabled(boolean enabled) {
		this.enabled = enabled;
	}

}
