package co.com.carpcosoftware.schoolmanagement.hibernate;

// Generated 19-abr-2015 18:35:39 by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * Bzuserxusertype generated by hbm2java
 */
public class Bzuserxusertype implements java.io.Serializable {

	private BzuserxusertypeId id;
	private Bzuser bzuser;
	private Cnusertype cnusertype;
	private Date creation;
	private Date updated;
	private boolean enabled;

	public Bzuserxusertype() {
	}

	public Bzuserxusertype(BzuserxusertypeId id, Bzuser bzuser,
			Cnusertype cnusertype, Date creation, Date updated, boolean enabled) {
		this.id = id;
		this.bzuser = bzuser;
		this.cnusertype = cnusertype;
		this.creation = creation;
		this.updated = updated;
		this.enabled = enabled;
	}

	public BzuserxusertypeId getId() {
		return this.id;
	}

	public void setId(BzuserxusertypeId id) {
		this.id = id;
	}

	public Bzuser getBzuser() {
		return this.bzuser;
	}

	public void setBzuser(Bzuser bzuser) {
		this.bzuser = bzuser;
	}

	public Cnusertype getCnusertype() {
		return this.cnusertype;
	}

	public void setCnusertype(Cnusertype cnusertype) {
		this.cnusertype = cnusertype;
	}

	public Date getCreation() {
		return this.creation;
	}

	public void setCreation(Date creation) {
		this.creation = creation;
	}

	public Date getUpdated() {
		return this.updated;
	}

	public void setUpdated(Date updated) {
		this.updated = updated;
	}

	public boolean isEnabled() {
		return this.enabled;
	}

	public void setEnabled(boolean enabled) {
		this.enabled = enabled;
	}

}
