package co.com.carpcosoftware.schoolmanagement.hibernate;

// Generated 19-abr-2015 18:35:39 by Hibernate Tools 4.3.1

/**
 * CnuserttypexaccessId generated by hbm2java
 */
public class CnusertypexaccessId implements java.io.Serializable {

	private int idUserType;
	private int idAccess;

	public CnusertypexaccessId() {
	}

	public CnusertypexaccessId(int idUserType, int idAccess) {
		this.idUserType = idUserType;
		this.idAccess = idAccess;
	}

	public int getIdUserType() {
		return this.idUserType;
	}

	public void setIdUserType(int idUserType) {
		this.idUserType = idUserType;
	}

	public int getIdAccess() {
		return this.idAccess;
	}

	public void setIdAccess(int idAccess) {
		this.idAccess = idAccess;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CnusertypexaccessId))
			return false;
		CnusertypexaccessId castOther = (CnusertypexaccessId) other;

		return (this.getIdUserType() == castOther.getIdUserType())
				&& (this.getIdAccess() == castOther.getIdAccess());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdUserType();
		result = 37 * result + this.getIdAccess();
		return result;
	}

}
