package co.com.carpcosoftware.schoolmanagement.hibernate;

// Generated 19-abr-2015 18:35:39 by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * Cnuserttypexaccess generated by hbm2java
 */
public class Cnuserttypexaccess implements java.io.Serializable {

	private CnuserttypexaccessId id;
	private Cnaccess cnaccess;
	private Cnusertype cnusertype;
	private Date creation;
	private Date updated;
	private boolean enabled;

	public Cnuserttypexaccess() {
	}

	public Cnuserttypexaccess(CnuserttypexaccessId id, Cnaccess cnaccess,
			Cnusertype cnusertype, Date creation, Date updated, boolean enabled) {
		this.id = id;
		this.cnaccess = cnaccess;
		this.cnusertype = cnusertype;
		this.creation = creation;
		this.updated = updated;
		this.enabled = enabled;
	}

	public CnuserttypexaccessId getId() {
		return this.id;
	}

	public void setId(CnuserttypexaccessId id) {
		this.id = id;
	}

	public Cnaccess getCnaccess() {
		return this.cnaccess;
	}

	public void setCnaccess(Cnaccess cnaccess) {
		this.cnaccess = cnaccess;
	}

	public Cnusertype getCnusertype() {
		return this.cnusertype;
	}

	public void setCnusertype(Cnusertype cnusertype) {
		this.cnusertype = cnusertype;
	}

	public Date getCreation() {
		return this.creation;
	}

	public void setCreation(Date creation) {
		this.creation = creation;
	}

	public Date getUpdated() {
		return this.updated;
	}

	public void setUpdated(Date updated) {
		this.updated = updated;
	}

	public boolean isEnabled() {
		return this.enabled;
	}

	public void setEnabled(boolean enabled) {
		this.enabled = enabled;
	}

}
